### PR TITLE
fix next-pool overrides by job

### LINKED ISSUE #2253: Copy job fails, because "Next Pool" is not accepted as an override in the job config.
### Bareos component version

Director: 23.1.3

### Steps to reproduce

Try to call an copy job, where the "Next pool" is only set in the job config.

### Expected results

That the copy job is executed.

### Actual results

Error message:
`22-Apr 10:05 Bareos Director JobId 0: Fatal error: No Next Pool specification found in Pool "SourcePool".`
But the [documentation](https://docs.bareos.org/Configuration/Director.html#config-Dir_Job_NextPool) say's:

> A Next Pool override used for Migration/Copy and Virtual Backup Jobs.

Therefore, if you overwrite undefined with defined, the result should be the overwritten value and not an error.
This means that the check as to whether there is a ‘next pool’ can only be carried out after all parameters have been analysed. Presumably the system simply checks whether there is a ‘Next Pool’ in the source pool, regardless of whether it is overwritten or not.

### Environment

```markdown
- OS: RHEL-8/9
```

### Relevant log output

```shell

```

### Relevant traces output

```shell

```

### Anything else?

Sample config:
Job:
```
Job {
        Name = "Test copy"
        Type = Copy
         # Jobdef only contain settings for update statistics and messages
        Job Defs = "WebUI"
        Pool = "SourcePool"
        Next Pool = "TargetPool"
        Selection Type = SQLQuery
        Selection Pattern = "select jobid from job where jobid=365279;"
}
```
Source pool:
```
Pool {
  Name = "SourcePool"
  Action On Purge = Truncate
  Job Retention = 1w
  File Retention = 1w
  Volume Retention = 1w
  Label Format = "Foo-"
  Maximum Volume Bytes = 1G
  Maximum Volumes = 60
  Storage = "Foo storage"
}
```
Target pool:
```
Pool {
  Name = "TargetPool"
  Action On Purge = Truncate
  Job Retention = 1w
  File Retention = 1w
  Volume Retention = 1w
  Label Format = "Bar-"
  Maximum Volume Bytes = 5G 
  Maximum Volumes = 100
  Storage = "Bar storage"
}
```

### PR DESCRIPTION
**Pull request by florian-at-bareos**
The next pool directive can be defined in the Pool and Job resource, the next pool directive in the Job resource should override the directive in the Pool resource. Currently, The directive in the job resource is not taken into account when running a job via the "run" command in the bconsole. This PR fixes this and takes the directive from the Job resource if specified.

Also, this PR adds a section in the copy-migrate systemtest to test the override behaviour of this directive.

Fixes #2253: Copy job fails, because "Next Pool" is not accepted as an override in the job config.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
~~Required backport PRs have been created~~
- [x] Correct milestone is set

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

##### Tests
- [x] Decision taken that a test is required (if not, then remove this paragraph)
- [x] The choice of the type of test (unit test or systemtest) is reasonable
- [x] Testname matches exactly what is being tested
- [x] On a fail, output of the test leads quickly to the origin of the fault

### CODE REVIEW

**Comment by florian-at-bareos** [comment]
The code is still awkward because the ScanCommandLineArguments method in ua_run.cc also sets values that are not given in the command line, applying overrides.

**Comment by florian-at-bareos** [comment]
Also, is the name of the method ResetRestoreContext in ua_run.cc correct? The method updates jcr->dir_impl->res values from a RunContext reference, no RestoreContext at all.

File: core/src/dird/ua_run.cc [hunk 1]
```diff
@@ -379,15 +378,15 @@ int DoRunCmd(UaContext* ua, const char*)
...
-    SetJcrDefaults(jcr, rc.job);
-    jcr->dir_impl->unlink_bsr
-        = ua->jcr->dir_impl->unlink_bsr; /* copy unlink flag from caller */
-    ua->jcr->dir_impl->unlink_bsr = false;
-  }
+  /* Create JobControlRecord to run job. */
+  auto jcr = std::unique_ptr<JobControlRecord,
+                             std::function<void(JobControlRecord*)>>(
+      NewDirectorJcr(DirdFreeJcr),
+      [&](JobControlRecord* to_delete) { FreeJcr(to_delete); });
```
Comment (sebsura) [inline core/src/dird/ua_run.cc]: Why does this lambda capture everything ?  It only accesses its only argument.

File: core/src/dird/ua_run.cc [hunk 2]
```diff
@@ -518,11 +517,6 @@ int DoRunCmd(UaContext* ua, const char*)
 
     return JobId;
   }
-
-bail_out:
-  ua->SendMsg(T_("Job not run.\n"));
```
Comment (sebsura) [inline core/src/dird/ua_run.cc]: What happened to this message ?

File: core/src/dird/ua_run.cc (hunk 1 above)
Comment (sebsura) [reply core/src/dird/ua_run.cc]: Im also not a fan of the std::function here.
If its possible maybe we can just do
```
auto* jcr = NewDirectorJcr(...);
auto res = FunctionWithAllTheLogic(jcr);
FreeJcr(jcr);
```
This may be easier to read.  A `unique_ptr` isnt just something that calls a destructor automatically for you: It signifies ownership.  Clearly this function is _not_ the single owner of this jcr, as we later pass it to `RunJob()`, which holds on to a reference.
This makes the code somewhat confusing to read for me, e.g. here:
```
    JobId = RunJob(jcr.get());
```
i was about to write a comment saying that you probably wanted to use `.release()`  here but that would be completely wrong!

jcr already has a builtin reference counting and is shared by default, so using a unique_ptr here is not the right call.
Maybe we can create our own JCR smart pointer for cases such as this.

Comment (florian-at-bareos) [reply core/src/dird/ua_run.cc]: I see! Do you think that it makes sense for me to work on that?
"Maybe we can create our own JCR smart pointer for cases such as this." sounds like it's a lot of effort. Do you have another idea on how to cleanly get rid of this "bail_out" goto or should i just rollback this for now?

Comment (arogge) [reply core/src/dird/ua_run.cc]: There's `finally` available in the GSL. That could replace `goto` at least in some cases. Not sure if it is worth the effort though.

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Re-finally

Comment (sebsura) [reply core/src/dird/ua_run.cc]: Yes either roll it back or try to use `gsl::finally`.  I would be fine with either of them.

**Review by sebsura — APPROVED** [review]
Looks good to me.  Thanks for the work!
