### PR TITLE
bconsole: require only one password in the configuration

### LINKED ISSUE #2083: bconsole should not require a password in its director configuration.
### Bareos component version

24+

### Steps to reproduce

1. Have a bconsole configuration with a console resource.
2. The bconsole will only use this password for connecting to the director
3. So the director should not need a useless password as well.

### PR DESCRIPTION
**Pull request by florian-at-bareos**
bconsole: director must not always have a password

Fixes #2083: bconsole should not require a password in its director configuration.

Remove 'required' flag from Password item in Director resource. If no
Password item is given, check whether a Console resource is provided
and if not abort.

Add Console resource to bareos-configparser-tests to test changes.

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created
- [x] Correct milestone is set

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

##### Tests
- [x] Decision taken that a test is required (if not, then remove this paragraph)
- [x] The choice of the type of test (unit test or systemtest) is reasonable
- [x] Testname matches exactly what is being tested
- [x] On a fail, output of the test leads quickly to the origin of the fault

### CODE REVIEW

File: core/src/console/console.cc [hunk 1]
```diff
@@ -1144,22 +1143,40 @@ static void TerminateConsole(int sig)
...
     OK = false;
   }
 
+  std::size_t console_count = 0;
+  for (BareosResource* console = nullptr;
+       (console = my_config->GetNextRes(R_CONSOLE, console));) {
+    ++console_count;
+  }
+
+  if (console_count == 0) {
```
Comment (sebsura) [inline core/src/console/console.cc:1168]: as we only care about having 0 consoles, we could simply do
```suggestion
  if (my_config->GetNextRes(R_CONSOLE, nullptr) == nullptr) {
```

Comment (sebsura) [reply core/src/console/console.cc:1168]: actually the same is true for the director `if()` as well, so you may as well change it there too.

Comment (sebsura) [reply core/src/console/console.cc:1168]: as we actually need access to the director resource anyways, maybe it makes sense to just define these right after the `ResLocker`:

```C++
  ResLocker _{my_config};
  auto* director = dynamic_cast<DirectorResource*>(my_config->GetNextRes(R_DIRECTOR, nullptr));
  auto* console = dynamic_cast<ConsoleResource*>(my_config->GetNextRes(R_CONSOLE, nullptr));
```

Then we can simply do `if (!director)` and `if (!console)`

File: core/src/console/console.cc [hunk 2]
```diff
@@ -1144,22 +1143,40 @@ static void TerminateConsole(int sig)
...
+    DirectorResource* director = dynamic_cast<DirectorResource*>(
+        my_config->GetNextRes(R_DIRECTOR, nullptr));
+    if (director->item_present_.find("Password")
+        == director->item_present_.end()) {
```
Comment (sebsura) [inline core/src/console/console.cc:1172]: We have a function for that:
```suggestion
    if (!director->IsMemberPresent("Password")) {
```

File: core/src/console/console.cc [hunk 3]
```diff
@@ -1144,22 +1143,40 @@ static void TerminateConsole(int sig)
...
+      Emsg2(
+          M_ABORT, 0,
+          T_("Password item is required in Director resource (since no Console "
+             "resource is specified), but not found.\n"));
+    }
+  }
+
```
Comment (sebsura) [inline core/src/console/console.cc:1179]: I guess the line below could also then just be `me = console`.

**Review by sebsura — CHANGES_REQUESTED** [review]

**Review by sebsura — CHANGES_REQUESTED** [review]
I noticed some small issues, but apart from these its basically ready for merging

**Review by sebsura — APPROVED** [review]
