### PR TITLE
fix autodeflate messages and refactor setup method

### LINKED ISSUE #1944: autoxflate lzo & visuals are broken
Currently the autodeflate setup code looks like this:

```C++
switch (autodeflate) {
...
#if defined(HAVE_LZO)
    case COMPRESS_LZO1X:
      compressorname = COMPRESSOR_NAME_LZO;
      break; // nothing is set up; is this intentional ?
#endif
 
    case COMPRESS_FZFZ:
      compressorname = COMPRESSOR_NAME_FZLZ;
      [[fallthrough]];
    case COMPRESS_FZ4L:
      compressorname = COMPRESSOR_NAME_FZ4L;
      [[fallthrough]];
    case COMPRESS_FZ4H: {
      compressorname = COMPRESSOR_NAME_FZ4H; // compressor name is always overriden to FZ4H
      ...
     }
  ...
}
Jmsg(ctx, M_INFO, T_("autoxflate-sd: Compressor on device %s is %s\n"),
     dcr->dev_name, compressorname);
```

We need to
- [x] Check if lzo compression works
- [ ] Fix the compressor name output if any FZ* algorithm is chosen.
       This can easily be done by checking `compressorname == COMPRESSOR_NAME_UNSET` before each assignment.

### PR DESCRIPTION
**Pull request by florian-at-bareos**
Fixes #1944: autoxflate lzo & visuals are broken

Remove switch statement to avoid dangerous fallthrough with code in
between which causes the problem (#1944) in the first place.

Note that I did a manual test and got the correct compressor names:
17-Jan 09:01 bareos-sd JobId 13: autoxflate-sd: Compressor on device FileStorage is LZ4
previously this would output LZ4HC besides LZ4 being specified

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
~~Required backport PRs have been created~~
- [x] Correct milestone is set

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

### CODE REVIEW

File: core/src/plugins/stored/autoxflate/autoxflate-sd.cc [hunk 1]
```diff
@@ -431,16 +431,15 @@ static bRC handle_write_translation(PluginContext* ctx, void* value)
 // Setup deflate for auto deflate of data streams.
 static bool SetupAutoDeflation(PluginContext* ctx, DeviceControlRecord* dcr)
```
Comment (sebsura) [inline core/src/plugins/stored/autoxflate/autoxflate-sd.cc:432]: The function `bool SetupCompressionContext(b_ctx& bctx)` in `filed/compression.cc` is very similar to this.
We should try to unify the logic of these functions.  One way would be to create a
```
bool SetupCompressionWorkset(JobControlRecord*, CompressionContext&, uint32_t algo);
```
that does what the switch is currently doing.
As the `autoxflate-sd.cc` wants the name of the compressor, maybe you can create a separate function
```
const char* compressor_name(uint32_t algo);
```
or something like that.

We could take this opportunity to also change the `#define`s in `ch.h`:

```C++
#include <cstdint>

namespace {
  constexpr std::uint32_t compression_constant(const char (&txt)[5])
{
  std::uint32_t a32 = txt[0];
  std::uint32_t b32 = txt[1];
  std::uint32_t c32 = txt[2];
  std::uint32_t d32 = txt[3];

  return (a32 << 24) | (b32 << 16) | (c32 << 8) | d32;
}
};

// Compression algorithm signature. 4 letters as a 32bits integer
enum compression_type : std::uint32_t {
  COMPRESS_NONE = compression_constant("NONE"), /* used for incompressible block */
  COMPRESS_GZIP = compression_constant("GZIP"),
  COMPRESS_LZO1X = compression_constant("LZOX"),
  COMPRESS_FZFZ = compression_constant("FZFZ"),
  COMPRESS_FZ4L = compression_constant("FZ4L"),
  COMPRESS_FZ4H = compression_constant("FZ4H"),
};

// double check our constants with the previously defined values
static_assert(0x4e4f4e45 == compression_constant("NONE"));
static_assert(0x475a4950 == compression_constant("GZIP"));
static_assert(0x4c5a4f58 == compression_constant("LZOX"));
static_assert(0x465A465A == compression_constant("FZFZ"));
static_assert(0x465A344C == compression_constant("FZ4L"));
static_assert(0x465A3448 == compression_constant("FZ4H"));
```
but this is just an example.

**Review by sebsura — CHANGES_REQUESTED** [review]

File: core/src/plugins/stored/autoxflate/autoxflate-sd.cc (hunk 1 above)
Comment (florian-at-bareos) [reply core/src/plugins/stored/autoxflate/autoxflate-sd.cc:425]: Sounds good! I tried including the suggestions

the static_asserts
// double check our constants with the previously defined values
static_assert(0x4e4f4e45 == compression_constant("NONE"));
static_assert(0x475a4950 == compression_constant("GZIP"));
static_assert(0x4c5a4f58 == compression_constant("LZOX"));
static_assert(0x465A465A == compression_constant("FZFZ"));
static_assert(0x465A344C == compression_constant("FZ4L"));
static_assert(0x465A3448 == compression_constant("FZ4H"));
succeeded and I removed them.

or you think I should leave them in the codebase?

Comment (sebsura) [reply core/src/plugins/stored/autoxflate/autoxflate-sd.cc:425]: I would leave them in there for now.

**Review by sebsura — CHANGES_REQUESTED** [review]

File: core/src/filed/compression.cc [hunk 2]
```diff
@@ -120,78 +118,23 @@ bool SetupCompressionContext(b_ctx& bctx)
...
-      case COMPRESS_FZ4H: {
-        int zstat;
-        zfast_stream* pZfastStream;
-        zfast_stream_compressor compressor = COMPRESSOR_FASTLZ;
-
-        /* Only change fastlz parameters if there is no pending operation.
-         * This should never happen as fastlzlibCompressReset is called after
-         * each fastlzlibCompress. */
-        pZfastStream = (zfast_stream*)bctx.jcr->compress.workset.pZFAST;
-        if (pZfastStream->total_in == 0) {
```
[the remark this answers is not in the document]
Comment (florian-at-bareos) [reply core/src/filed/compression.cc:167]: makes sense!

**Review by sebsura — APPROVED** [review]

File: core/cmake/BareosCopyDllsToBinDir.cmake [hunk 3]
```diff
@@ -30,6 +30,7 @@ macro(BareosCopyDllsToBinDir)
     set(FNAME "${CMAKE_BINARY_DIR}/required_dlls")
     set(DLLS_TO_COPY_MANUALLY C:/vcpkg/installed/x64-windows/bin/jansson.dll
                               C:/vcpkg/installed/x64-windows/bin/lzo2.dll
+                              C:/vcpkg/installed/x64-windows/bin/zlub1.dll
```
Comment (sebsura) [inline core/cmake/BareosCopyDllsToBinDir.cmake:33]: Didnt you mean zlib1 here ?
